if NAME="Contact_Type" then do;
ROLE="REJECTED";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="Mortage" then do;
ROLE="REJECTED";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="Number_of_Contacts" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="Personal_Loan" then do;
ROLE="REJECTED";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="Subscribed" then do;
ROLE="TARGET";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="VAR1" then do;
ROLE="REJECTED";
LEVEL="NOMINAL";
ORDER="";
end;
drop DROP;
